### PR TITLE
Added support for ESP8266 boards

### PR DESCRIPTION
**Pull request by xmichael**
Added support for ESP8266 boards like Adafruit HUZZAH. Works out of the box with vanilla Adafruit-GFX.

### CODE REVIEW

**Comment by mcauser** [comment]
This does not work on my WeMos D1 Mini (ESP-12F) on Arduino ESP8266 2.0.0
May be fixed in 2.1.0:
https://github.com/esp8266/Arduino/issues/1110

**Comment by Makuna** [comment]
Is there a reason this is not merged in? 
I don't understand since Adafruit also sells a esp8266 board?
I would change and use the more standard ARDUINO_ARCH_ESP8266 instead of ESP8266; but both work.

**Comment by WereCatf** [comment]
@Makuna The Adafruit - people are terrible at maintaining their own stuff; they have like a million different pull-requests across their libraries, most of the pull-requests being useful, and they go wholly unattended to for years. Even just replying why it's not being accepted would be more useful than letting them linger.

**Comment by mcauser** [comment]
I think they are more busy working on new products than maintaining very old products, which makes business sense. If the open source community are going to help by adding features or adding support/compatibility for other Adafruit products, they could at least have a look at the PRs or if they are too busy, perhaps enlist help from the community. Perhaps raising this in the Adafruit Forums may have more traction than here.

If you are Adafruit staff, thanks for the great libraries. Let us help improve them!

**Comment by drak7** [comment]
Closed in favor of #47

**Pull request closed without merging**
