### PR TITLE
Implement SPI-transactions and invertDisplay()

### PR DESCRIPTION
**Pull request by WereCatf**
Implement support for SPI-transactions so the library will play nice together with other SPI-devices with differing settings, and add the missing invertDisplay() - function.

### CODE REVIEW

**Comment by andrumar10** [comment]
Haha I thought I was being smart by trying to add in the invertDisplay() as my first ever pull request and it looks like it's already been done. Thanks for the SPI stuff too, its a shame adafruit will probably never get around to merging it.

**Comment by WereCatf** [comment]
Yeah, one would think they'd appreciate pull-requests and would keep their stuff up-to-date since they sell the stuff, but apparently no -- it's the same with with all of their stuff, it seems. It seems it's best to search around if there's a version of a library maintained by someone else, since those often have way more features and support more devices, and only resort to Adafruit's ones if there isn't such a library available elsewhere.

Oh well.

**Comment by elandesign** [comment]
I've just had to monkey patch the same functionality into my project - I was about to fork the library and submit a pull request myself, but spotted this first.

+1 from me for getting this merged if possible.

**Comment by ladyada** [comment]
re-implemented correctly in a different pr

**Pull request closed without merging**
