### PR TITLE
Changes for the ESP8266

### PR DESCRIPTION
**Pull request by bbx10**
Changes to make the driver work on the ESP8266. pcdtest.ino works on the ESP8266.

Also the following uses this version.

https://github.com/bbx10/esp-pcd-bitcoin

### CODE REVIEW

**Comment by mcauser** [comment]
This works on my WeMos D1 Mini (ESP-12F) using both software and hardware SPI.
Had to increase contrast to 60 as 50 is a little patchy.

**Comment by maurbeck** [comment]
What is the status on this? Is it possible to accept this pull request?

**Comment by mcauser** [comment]
@tdicola Do you have a minute to review this PR?
This unblocks me from using this library on my Adafruit Huzzah ESP8266 and Feather Huzzah.
Thanks

**Comment by gamecompiler** [comment]
Cant this branch me merged?

**Comment by vinceskahan** [comment]
please merge this finally (I  dunno why it's 'closed') - the PR works great on my nodeMCU card and is needed to be able to drive a 5110 display.

**Comment by drak7** [comment]
Closed in favor of #47

**Pull request closed without merging**
