### PR TITLE
pcdtest: Add option to reinitialize display repeatedly in case of bad…

### PR DESCRIPTION
**Pull request by hramrach**
… contact

Disable the refresh by default in pdctest (untested, don't have the environment at hand).

### CODE REVIEW

**Comment by hramrach** [comment]
Something is wrong with the Travis result caching. The check is shown as failed but the build log shows success.

**Comment by siddacious** [comment]
@hramrach it's perhaps non-obvious but the travis build is failing on Doxygen documentation warnings/errors.

Check the warnings in red at the bottom of the page and let us know if you need help addressing them. 

Thank you!

**Comment by hramrach** [comment]
@siddacious I am pretty sure that the majority of these warnings were not introduced by this commit. If you want to check documentation coverage in Travis fix your project documentation on master branch first.

**Comment by drak7** [comment]
Don't worry about the Travis check, we're in the process of adding Doxygen to this library.

**Pull request merged**
