### PR TITLE
Added option to set backlight pin to adjust brightness with pwm

### PR DESCRIPTION
**Pull request by Gust09**
Added option to set backlight pin to adjust brightness with pwm

### CODE REVIEW

**Comment by drak7** [comment]
Good idea! It would make more sense to have backlightPin as a private class member (like _rst, _dc, etc) and then set it in the constructor. Then you'd just need the setBacklight method. That should be defined in the class definition as well (in the .h file).

**Comment by bxparks** [comment]
Drive-by comment: 

The other problem with this PR is that it assumes that the PWM pin uses an 8-bit value. But many 32-bit processors (e.g. ESP8266) uses a 10-bit PWM, which would not work with this PR. One solution is to change the `uint8_t` to a `uint16_t`, which has the small drawback that it increases static RAM consumption on 8-bit processors by one byte, plus a few extra bytes in flash due to the increased code size.

My thoughts on this PR though is that this library should stay simple, and focused on the graphics rendering, and ignore the backlight functionality of the LCD. It is easy for the client code to call the `analogWrite()` on the pin directly. And the PR over 3 years old, so we can probably just drop it.

**Comment by bxparks** [comment]
The third problem with this PR is that it assumes that the backlight LEDs are directly pulled LOW by the analog pin (so that PWM 0 means brightest, and PWM 255 means dimmest/off). But some analog pins cannot pull the ~40mA of current that the 4 LEDs can draw. If an NPN driver transistor is installed, then the logic becomes inverted, so 255 (or 1023) means the brightest. I don't think it's worth putting in that kind of configuration complexity into this library. The client code will know how the LEDs are wired, so it can determine which PWM values correspond to "bright" and "dim".

**Comment by ladyada** [comment]
yah tbh since pwm isnt consistant in some ports, its best to handle the PWM/backlight separately!

**Pull request closed without merging**
